import type { Work } from "@/content/types";

/** Production works — Todd creative worlds. */
export const defaultWorksSeed: Work[] = [
  {
    id: `08`,
    slug: `the-northern-times`,
    title: `Never Grow Up`,
    describe: `A flagship canvas series celebrating childlike humor, blunt punchlines, and the belief that growing up is optional.`,
    client: `Original Art`,
    date: `2024`,
    services: `Illustrations`,
    category: `Original Art`,
    hook: `Growing up is optional.`,
    accentTone: `yellow`,
    featured: true,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-3057b619.png`, alt: `Never Grow Up — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-78b8d432.png`, alt: `Never Grow Up preview` },
    detailHero: { src: `/assets/images/image-e9e74d38.png`, alt: `Never Grow Up hero` },
    gallery: [
      { src: `/assets/images/image-542f70bb.png`, alt: `Never Grow Up detail 1` },
      { src: `/assets/images/image-562272dc.png`, alt: `Never Grow Up detail 2` },
      { src: `/assets/images/image-13ebfa5e.png`, alt: `Never Grow Up detail 3` },
    ],
    prevSlug: "nitty-craft-co",
    nextSlug: null,
  },
  {
    id: `07`,
    slug: `nitty-craft-co`,
    title: `Stupid Factory Characters`,
    describe: `Recurring doodled characters with schoolyard wit — the visual language behind David & Goliath and Todd's pop-art universe.`,
    client: `Characters & Humor`,
    date: `2023`,
    services: `Character design`,
    category: `Characters & Humor`,
    hook: `Drawn like a kid. Aimed at adults.`,
    accentTone: `red`,
    featured: false,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-57b50b25.png`, alt: `Stupid Factory Characters — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-c54e57a6.png`, alt: `Stupid Factory Characters preview` },
    detailHero: { src: `/assets/images/image-93443900.png`, alt: `Stupid Factory Characters hero` },
    gallery: [
      { src: `/assets/images/image-b3a2f420.png`, alt: `Stupid Factory Characters detail 1` },
      { src: `/assets/images/image-7bd0cc7f.png`, alt: `Stupid Factory Characters detail 2` },
      { src: `/assets/images/image-5853f4fc.png`, alt: `Stupid Factory Characters detail 3` },
    ],
    prevSlug: "oxbridge-press",
    nextSlug: "the-northern-times",
  },
  {
    id: `06`,
    slug: `oxbridge-press`,
    title: `Boys Are Stupid (Book Series)`,
    describe: `Publishing venture that turned irreverent slogans into bestsellers — proof that humor on a page hits as hard as humor on a shirt.`,
    client: `Books & Publishing`,
    date: `2022`,
    services: `Illustrated books`,
    category: `Books & Publishing`,
    hook: `50+ titles. Zero art-school pretension.`,
    accentTone: `blue`,
    featured: true,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-817d57df.png`, alt: `Boys Are Stupid — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-b6e2ba92.png`, alt: `Boys Are Stupid preview` },
    detailHero: { src: `/assets/images/image-d82472a8.png`, alt: `Boys Are Stupid hero` },
    gallery: [
      { src: `/assets/images/image-1f579f15.png`, alt: `Boys Are Stupid detail 1` },
      { src: `/assets/images/image-43fb8c26.png`, alt: `Boys Are Stupid detail 2` },
      { src: `/assets/images/image-64d8dab1.png`, alt: `Boys Are Stupid detail 3` },
    ],
    prevSlug: "barcelona-civic-office",
    nextSlug: "nitty-craft-co",
  },
  {
    id: `05`,
    slug: `barcelona-civic-office`,
    title: `David & Goliath Apparel`,
    describe: `The global pop-art brand that started on T-shirts — bold graphics, sarcastic slogans, and smart-aleck optimism worn by millions.`,
    client: `Apparel & Licensing`,
    date: `2021`,
    services: `Merchandise & licensing`,
    category: `Apparel & Licensing`,
    hook: `From doodles to department stores.`,
    accentTone: `green`,
    featured: false,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-431c59fd.png`, alt: `David & Goliath Apparel — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-3a1db525.png`, alt: `David & Goliath Apparel preview` },
    detailHero: { src: `/assets/images/image-764f72b5.png`, alt: `David & Goliath Apparel hero` },
    gallery: [
      { src: `/assets/images/image-aab18db9.png`, alt: `David & Goliath Apparel detail 1` },
      { src: `/assets/images/image-e729c9bb.png`, alt: `David & Goliath Apparel detail 2` },
      { src: `/assets/images/image-f41afa00.png`, alt: `David & Goliath Apparel detail 3` },
    ],
    prevSlug: "südstadt-zeitung",
    nextSlug: "oxbridge-press",
  },
  {
    id: `04`,
    slug: `südstadt-zeitung`,
    title: `Gallery Pop Art`,
    describe: `Fine-art canvases with Day-Glo palettes and acrylic energy — art you can enjoy seven days a week and it still makes you happy.`,
    client: `Original Art`,
    date: `2021`,
    services: `Gallery paintings`,
    category: `Original Art`,
    hook: `Not museum art. Museum-sized laughs.`,
    accentTone: `yellow`,
    featured: false,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-6a3bd1b1.png`, alt: `Gallery Pop Art — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-6a3bd1b1.png`, alt: `Gallery Pop Art preview` },
    detailHero: { src: `/assets/images/image-d81a4938.png`, alt: `Gallery Pop Art hero` },
    gallery: [
      { src: `/assets/images/image-44c9c977.png`, alt: `Gallery Pop Art detail 1` },
      { src: `/assets/images/image-aaf0b289.png`, alt: `Gallery Pop Art detail 2` },
      { src: `/assets/images/image-d687d066.png`, alt: `Gallery Pop Art detail 3` },
    ],
    prevSlug: "monochrome-journal",
    nextSlug: "barcelona-civic-office",
  },
  {
    id: `03`,
    slug: `monochrome-journal`,
    title: `Animal Soup & Kids Books`,
    describe: `Children's titles that keep the doodle spirit alive for younger readers — playful, witty, and emotionally honest.`,
    client: `Books & Publishing`,
    date: `2020`,
    services: `Children's books`,
    category: `Books & Publishing`,
    hook: `Kid books. Adult humor optional.`,
    accentTone: `blue`,
    featured: false,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-7fb09da3.png`, alt: `Animal Soup & Kids Books — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-7fb09da3.png`, alt: `Animal Soup & Kids Books preview` },
    detailHero: { src: `/assets/images/image-089bc01d.png`, alt: `Animal Soup & Kids Books hero` },
    gallery: [
      { src: `/assets/images/image-d268e6b6.png`, alt: `Animal Soup & Kids Books detail 1` },
      { src: `/assets/images/image-b017d0ef.png`, alt: `Animal Soup & Kids Books detail 2` },
      { src: `/assets/images/image-a6752218.png`, alt: `Animal Soup & Kids Books detail 3` },
    ],
    prevSlug: "the-economic-review",
    nextSlug: "südstadt-zeitung",
  },
  {
    id: `02`,
    slug: `the-economic-review`,
    title: `Licensed Collaborations`,
    describe: `Brand partnerships and licensed products that extend Todd's visual world into retail, gifts, and custom collections.`,
    client: `Collaborations`,
    date: `2019`,
    services: `Brand licensing`,
    category: `Collaborations`,
    hook: `Your brand. Todd's twisted mind.`,
    accentTone: `red`,
    featured: true,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-38decee6.png`, alt: `Licensed Collaborations — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-38decee6.png`, alt: `Licensed Collaborations preview` },
    detailHero: { src: `/assets/images/image-b899b32a.png`, alt: `Licensed Collaborations hero` },
    gallery: [
      { src: `/assets/images/image-eedc20fc.png`, alt: `Licensed Collaborations detail 1` },
      { src: `/assets/images/image-7859700e.png`, alt: `Licensed Collaborations detail 2` },
      { src: `/assets/images/image-56d29d14.png`, alt: `Licensed Collaborations detail 3` },
    ],
    prevSlug: "the-chronicle",
    nextSlug: "monochrome-journal",
  },
  {
    id: `01`,
    slug: `the-chronicle`,
    title: `Todd Art™ Shop`,
    describe: `The current retail home for prints, mugs, and collectibles — playful, witty artwork that feels familiar the moment you see it.`,
    client: `Apparel & Licensing`,
    date: `2019`,
    services: `Retail & e-commerce`,
    category: `Apparel & Licensing`,
    hook: `Art you forgot you loved.`,
    accentTone: `green`,
    featured: false,
    ctaHref: "https://www.toddart.com/",
    ctaLabel: "Visit Shop",
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-f00bacf4.png`, alt: `Todd Art™ Shop — placeholder artwork` },
    hoverPreview: { src: `/assets/images/image-f00bacf4.png`, alt: `Todd Art™ Shop preview` },
    detailHero: { src: `/assets/images/image-cecb091c.png`, alt: `Todd Art™ Shop hero` },
    gallery: [
      { src: `/assets/images/image-5ceac62b.png`, alt: `Todd Art™ Shop detail 1` },
      { src: `/assets/images/image-8e1468db.png`, alt: `Todd Art™ Shop detail 2` },
      { src: `/assets/images/image-879261a8.png`, alt: `Todd Art™ Shop detail 3` },
    ],
    prevSlug: null,
    nextSlug: "the-economic-review",
  },
];
