import type { Work } from "@/content/types";

export const referenceWorksSeed: Work[] = [
  {
    id: `08`,
    slug: `the-northern-times`,
    title: `The Northern Times`,
    describe: `We built the visual system around clarity and rhythm — reflecting how news moves in real time. Modular layouts, bold typography, and restrained color allow stories to take center stage without distraction. The result is a system that adapts seamlessly across platforms, from fast-moving digital feeds to long-form editorial.`,
    client: `The Northern Times`,
    date: `2024`,
    services: `Illustrations`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-3057b619.png`, alt: `The Northern Times thumbnail` },
    hoverPreview: { src: `/assets/images/image-78b8d432.png`, alt: `The Northern Times preview` },
    detailHero: { src: `/assets/images/image-e9e74d38.png`, alt: `The Northern Times hero` },
    gallery: [
      { src: `/assets/images/image-542f70bb.png`, alt: `The Northern Times detail 1` },
      { src: `/assets/images/image-562272dc.png`, alt: `The Northern Times detail 2` },
      { src: `/assets/images/image-13ebfa5e.png`, alt: `The Northern Times detail 3` },
    ],
    prevSlug: "nitty-craft-co",
    nextSlug: null,
  },
  {
    id: `07`,
    slug: `nitty-craft-co`,
    title: `Nitty Craft Co.`,
    describe: `We approached the brand through tactility — bold forms, raw textures, and playful compositions. The packaging system feels hands-on and expressive, turning everyday products into small collectible objects. Each element was designed to feel unique yet cohesive, encouraging interaction and repeat engagement.`,
    client: `Nitty Craft Co.`,
    date: `2023`,
    services: `Packaging`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-57b50b25.png`, alt: `Nitty Craft Co. thumbnail` },
    hoverPreview: { src: `/assets/images/image-c54e57a6.png`, alt: `Nitty Craft Co. preview` },
    detailHero: { src: `/assets/images/image-93443900.png`, alt: `Nitty Craft Co. hero` },
    gallery: [
      { src: `/assets/images/image-b3a2f420.png`, alt: `Nitty Craft Co. detail 1` },
      { src: `/assets/images/image-7bd0cc7f.png`, alt: `Nitty Craft Co. detail 2` },
      { src: `/assets/images/image-5853f4fc.png`, alt: `Nitty Craft Co. detail 3` },
    ],
    prevSlug: "oxbridge-press",
    nextSlug: "the-northern-times",
  },
  {
    id: `06`,
    slug: `oxbridge-press`,
    title: `Oxbridge Press`,
    describe: `The concept focused on timelessness and precision. A refined typographic system paired with subtle illustration details creates a balance between academic heritage and contemporary publishing. This approach ensures consistency across a wide range of publications while maintaining a distinct identity.`,
    client: `Paramount Comedy Ident`,
    date: `2022`,
    services: `Illustrations`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-817d57df.png`, alt: `Oxbridge Press thumbnail` },
    hoverPreview: { src: `/assets/images/image-b6e2ba92.png`, alt: `Oxbridge Press preview` },
    detailHero: { src: `/assets/images/image-d82472a8.png`, alt: `Oxbridge Press hero` },
    gallery: [
      { src: `/assets/images/image-1f579f15.png`, alt: `Oxbridge Press detail 1` },
      { src: `/assets/images/image-43fb8c26.png`, alt: `Oxbridge Press detail 2` },
      { src: `/assets/images/image-64d8dab1.png`, alt: `Oxbridge Press detail 3` },
    ],
    prevSlug: "barcelona-civic-office",
    nextSlug: "nitty-craft-co",
  },
  {
    id: `05`,
    slug: `barcelona-civic-office`,
    title: `Barcelona Civic Office`,
    describe: `We developed a flexible identity system designed to unify diverse city initiatives. Bright colors, simple shapes, and clear hierarchy make communication accessible across digital and physical spaces. The system scales easily, supporting everything from public signage to campaign materials.`,
    client: `Barcelona Civic Office`,
    date: `2021`,
    services: `Brand Identity`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-431c59fd.png`, alt: `Barcelona Civic Office thumbnail` },
    hoverPreview: { src: `/assets/images/image-3a1db525.png`, alt: `Barcelona Civic Office preview` },
    detailHero: { src: `/assets/images/image-764f72b5.png`, alt: `Barcelona Civic Office hero` },
    gallery: [
      { src: `/assets/images/image-aab18db9.png`, alt: `Barcelona Civic Office detail 1` },
      { src: `/assets/images/image-e729c9bb.png`, alt: `Barcelona Civic Office detail 2` },
      { src: `/assets/images/image-f41afa00.png`, alt: `Barcelona Civic Office detail 3` },
    ],
    prevSlug: "s\u00fcdstadt-zeitung",
    nextSlug: "oxbridge-press",
  },
  {
    id: `04`,
    slug: `südstadt-zeitung`,
    title: `Südstadt Zeitung`,
    describe: `The design explores contrast — tradition and modernity coexisting. Clean grids meet expressive editorial accents, creating a visual language that feels both familiar and forward-looking. This balance helps the publication stand out while remaining approachable to a broad audience.`,
    client: `Südstadt Zeitung`,
    date: `2021`,
    services: `Illustration`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-6a3bd1b1.png`, alt: `Südstadt Zeitung thumbnail` },
    hoverPreview: { src: `/assets/images/image-6a3bd1b1.png`, alt: `Südstadt Zeitung preview` },
    detailHero: { src: `/assets/images/image-d81a4938.png`, alt: `Südstadt Zeitung hero` },
    gallery: [
      { src: `/assets/images/image-44c9c977.png`, alt: `Südstadt Zeitung detail 1` },
      { src: `/assets/images/image-aaf0b289.png`, alt: `Südstadt Zeitung detail 2` },
      { src: `/assets/images/image-d687d066.png`, alt: `Südstadt Zeitung detail 3` },
    ],
    prevSlug: "monochrome-journal",
    nextSlug: "barcelona-civic-office",
  },
  {
    id: `03`,
    slug: `monochrome-journal`,
    title: `Monochrome Journal`,
    describe: `We stripped everything back to essentials. A minimal palette and sharp typographic rhythm create a calm, focused reading experience where content defines the aesthetic. The reduced visual noise allows each story to resonate more clearly with the reader.`,
    client: `Monochrome Journal`,
    date: `2020`,
    services: `Art direction`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-7fb09da3.png`, alt: `Monochrome Journal thumbnail` },
    hoverPreview: { src: `/assets/images/image-7fb09da3.png`, alt: `Monochrome Journal preview` },
    detailHero: { src: `/assets/images/image-089bc01d.png`, alt: `Monochrome Journal hero` },
    gallery: [
      { src: `/assets/images/image-d268e6b6.png`, alt: `Monochrome Journal detail 1` },
      { src: `/assets/images/image-b017d0ef.png`, alt: `Monochrome Journal detail 2` },
      { src: `/assets/images/image-a6752218.png`, alt: `Monochrome Journal detail 3` },
    ],
    prevSlug: "the-economic-review",
    nextSlug: "s\u00fcdstadt-zeitung",
  },
  {
    id: `02`,
    slug: `the-economic-review`,
    title: `The Economic Review`,
    describe: `We centered the identity around structure and data. Precise layouts, subtle motion, and analytical visual cues reinforce clarity and trust in complex information. The system supports both quick insights and in-depth analysis without compromising readability.`,
    client: `The Economic Review`,
    date: `2019`,
    services: `Illustration`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-38decee6.png`, alt: `The Economic Review thumbnail` },
    hoverPreview: { src: `/assets/images/image-38decee6.png`, alt: `The Economic Review preview` },
    detailHero: { src: `/assets/images/image-b899b32a.png`, alt: `The Economic Review hero` },
    gallery: [
      { src: `/assets/images/image-eedc20fc.png`, alt: `The Economic Review detail 1` },
      { src: `/assets/images/image-7859700e.png`, alt: `The Economic Review detail 2` },
      { src: `/assets/images/image-56d29d14.png`, alt: `The Economic Review detail 3` },
    ],
    prevSlug: "the-chronicle",
    nextSlug: "monochrome-journal",
  },
  {
    id: `01`,
    slug: `the-chronicle`,
    title: `The Chronicle`,
    describe: `The system is built on narrative flow — guiding the reader through layered stories. Warm tones, editorial typography, and soft transitions create a more human, immersive news experience. This approach strengthens emotional connection while preserving editorial credibility.`,
    client: `The Chronicle`,
    date: `2019`,
    services: `Art Direction`,
    relatedTitle: `Paramount Comedy Ident`,
    gridThumbnail: { src: `/assets/images/image-f00bacf4.png`, alt: `The Chronicle thumbnail` },
    hoverPreview: { src: `/assets/images/image-f00bacf4.png`, alt: `The Chronicle preview` },
    detailHero: { src: `/assets/images/image-cecb091c.png`, alt: `The Chronicle hero` },
    gallery: [
      { src: `/assets/images/image-5ceac62b.png`, alt: `The Chronicle detail 1` },
      { src: `/assets/images/image-8e1468db.png`, alt: `The Chronicle detail 2` },
      { src: `/assets/images/image-879261a8.png`, alt: `The Chronicle detail 3` },
    ],
    prevSlug: null,
    nextSlug: "the-economic-review",
  },
];
